### PR TITLE
Quick typo fix

### PR DESCRIPTION
**Pull request by sqtran**
Just a quick typo fix!

### CODE REVIEW

**Comment by benmccann** [comment]
If you rebase against master then Travis should pass now

**Comment by sqtran** [comment]
Ready to merge into master :muscle:

**Comment by benmccann** [comment]
Hmm. I'm not sure why the commits for fixing the build and releasing 2.3.1 are on your PR. New commits shouldn't typically show up on a rebased PR

**Comment by sqtran** [comment]
I messed up and rebased my branch directly from upstream.  What I should have done was rebase my master from upstream, then merge my patch branch and rebase it to fast-forward all the new changes.  If all done correctly, I should have only my 1 typo change at the top of my patch branch.  Since I already pushed to my local repo, the history looks super messy now.  I'll close this PR and create a new PR with the correct history.

**Pull request closed without merging**
