### PR TITLE
Fix the build. Upgrade non-gitbook dependencies

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@SamyPesse would you be able to take a look at this one? thanks!

**Comment by benmccann** [comment]
@SamyPesse I wanted to get your thoughts on this one. Thanks

**Comment by benmccann** [comment]
just a friendly reminder to please take a look at this PR

**Comment by benmccann** [comment]
@SamyPesse just a gentle reminder to merge this when you get a chance. thanks!

**Comment by benmccann** [comment]
@SamyPesse any reason not to merge this to fix the build?

**Comment by benmccann** [comment]
@AaronO @dylang @sindresorhus @SamyPesse @Zhouzi would you be able to merge this PR to fix the build?

**Comment by AaronO** [comment]
Thanks @benmccann, those changes make sense 👍

**Comment by AaronO** [comment]
@benmccann Sorry for the delayed replies. The team's efforts have been focused on a major product release (`gitbook.com`, editor, ...)  that we'll announce later this week.

**Comment by benmccann** [comment]
Thanks! Any chance it'd be possible to get a new release?

The current version of gitbook-cli is not compatible with npm5 because it has corrupted dependencies. This PR should fix it. See https://github.com/npm/npm/issues/17081

**Comment by AaronO** [comment]
@benmccann Yes, I just minted a `2.3.1` release. Give that a try and let me know if it fixes your issue.

**Comment by benmccann** [comment]
Thank you! That did fix it!

**Pull request merged**
